#!/usr/bin/env bun
// session-capture.ts
// Stop hook: Capture session summary to MEMORY/sessions/
// ISOLATED MODE: Each project keeps its own memory, no cross-pollution
// - Project with MEMORY/ → saves only there
// - No MEMORY/ → falls back to ai-brain

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, basename } from 'path';
import { homedir } from 'os';

interface StopPayload {
  session_id: string;
  cwd?: string;
  [key: string]: any;
}

function getLocalTimestamp(): string {
  const date = new Date();
  const tz = process.env.TIME_ZONE || Intl.DateTimeFormat().resolvedOptions().timeZone;

  try {
    const localDate = new Date(date.toLocaleString('en-US', { timeZone: tz }));
    const year = localDate.getFullYear();
    const month = String(localDate.getMonth() + 1).padStart(2, '0');
    const day = String(localDate.getDate()).padStart(2, '0');
    const hours = String(localDate.getHours()).padStart(2, '0');
    const minutes = String(localDate.getMinutes()).padStart(2, '0');
    const seconds = String(localDate.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day}T${hours}:${minutes}:${seconds}`;
  } catch {
    return new Date().toISOString();
  }
}

function getDateString(): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function findProjectMemory(cwd: string): string | null {
  // Check if cwd has MEMORY/sessions/ directory
  const localMemory = join(cwd, 'MEMORY', 'sessions');
  if (existsSync(localMemory)) {
    return localMemory;
  }
  return null;
}

function getProjectName(cwd: string): string {
  return basename(cwd);
}

async function main() {
  try {
    const stdinData = await Bun.stdin.text();
    if (!stdinData.trim()) {
      process.exit(0);
    }

    const payload: StopPayload = JSON.parse(stdinData);
    const cwd = payload.cwd || process.cwd();
    const sessionId = payload.session_id || 'unknown';
    const shortId = sessionId.substring(0, 8);
    const dateStr = getDateString();
    const timestamp = getLocalTimestamp();
    const filename = `${dateStr}-${shortId}.md`;
    const projectName = getProjectName(cwd);

    // Check for local project MEMORY
    const localMemoryDir = findProjectMemory(cwd);

    // Determine where to save (project local OR ai-brain, not both)
    let targetDir: string;
    let location: string;

    if (localMemoryDir) {
      // Project has its own MEMORY - save only there
      targetDir = localMemoryDir;
      location = `${projectName}/MEMORY/sessions`;
    } else {
      // No local MEMORY - fall back to ai-brain
      targetDir = join(homedir(), 'ai-brain', 'MEMORY', 'sessions');
      location = 'ai-brain/MEMORY/sessions';
    }

    // Ensure directory exists
    if (!existsSync(targetDir)) {
      mkdirSync(targetDir, { recursive: true });
    }

    // Session content
    const content = `---
session_id: ${sessionId}
timestamp: ${timestamp}
cwd: ${cwd}
project: ${projectName}
---

# Session ${shortId}

**Date:** ${dateStr}
**Project:** ${projectName}
**Working directory:** ${cwd}

## Summary

Session captured automatically by stop hook.

---
*Auto-generated by session-capture.ts*
`;

    // Save to determined location
    const filepath = join(targetDir, filename);
    writeFileSync(filepath, content);
    console.error(`[PAI] Session captured: ${location}/${filename}`);

  } catch (error) {
    // Never crash - just log
    console.error('Session capture error:', error);
  }

  process.exit(0);
}

main();
