#!/usr/bin/env bun
// session-capture.ts
// Stop hook: Capture session summary to MEMORY/sessions/

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

interface StopPayload {
  session_id: string;
  cwd?: string;
  [key: string]: any;
}

function getLocalTimestamp(): string {
  const date = new Date();
  const tz = process.env.TIME_ZONE || Intl.DateTimeFormat().resolvedOptions().timeZone;

  try {
    const localDate = new Date(date.toLocaleString('en-US', { timeZone: tz }));
    const year = localDate.getFullYear();
    const month = String(localDate.getMonth() + 1).padStart(2, '0');
    const day = String(localDate.getDate()).padStart(2, '0');
    const hours = String(localDate.getHours()).padStart(2, '0');
    const minutes = String(localDate.getMinutes()).padStart(2, '0');
    const seconds = String(localDate.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day}T${hours}:${minutes}:${seconds}`;
  } catch {
    return new Date().toISOString();
  }
}

function getDateString(): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

async function main() {
  try {
    const stdinData = await Bun.stdin.text();
    if (!stdinData.trim()) {
      process.exit(0);
    }

    const payload: StopPayload = JSON.parse(stdinData);

    // ai-brain MEMORY directory
    const memoryDir = join(homedir(), 'ai-brain', 'MEMORY', 'sessions');

    // Ensure directory exists
    if (!existsSync(memoryDir)) {
      mkdirSync(memoryDir, { recursive: true });
    }

    // Create session file
    const sessionId = payload.session_id || 'unknown';
    const shortId = sessionId.substring(0, 8);
    const dateStr = getDateString();
    const filename = `${dateStr}-${shortId}.md`;
    const filepath = join(memoryDir, filename);

    const timestamp = getLocalTimestamp();
    const cwd = payload.cwd || 'unknown';

    // Write session file with YAML frontmatter
    const content = `---
session_id: ${sessionId}
timestamp: ${timestamp}
cwd: ${cwd}
---

# Session ${shortId}

**Date:** ${dateStr}
**Working directory:** ${cwd}

## Summary

Session captured automatically by stop hook.

---
*Auto-generated by session-capture.ts*
`;

    writeFileSync(filepath, content);
    console.error(`[PAI] Session captured: ${filename}`);

  } catch (error) {
    // Never crash - just log
    console.error('Session capture error:', error);
  }

  process.exit(0);
}

main();
